### ISSUE TITLE
readme code block language

### ISSUE THREAD

**Issue by david-fong** [kelvinkoon/leetcode_ft_may2020#1]
You can get syntax highlighting in GitHub by specifying python as the language for your readme;s code blocks.

https://www.markdownguide.org/extended-syntax/#syntax-highlighting

Happy leeting!

**Comment by kelvinkoon** [comment]
I didn't think anyone would actually read this. I unprivated the repo for a friend 😆 .
Thanks for letting me know, I'll keep that in mind!
